Ignore "stringop-overflow" warning in strncpy.
This will supress the following warning given by certain libc
versions. (Specifically, this was discovered on Ubuntu 20.04.)

/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error:
'__builtin_strncpy' specified bound depends on the length of the
source argument [-Werror=stringop-overflow=]

This will be used until a more principled solution is written.